name: Build and Push to Quay

on:
  push:
    branches:
      - main

env:
  FULL_IMAGE: quay.io/rh_ee_jfont/shiftleft:v1

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Build container image
        run: |
          docker build -t $FULL_IMAGE .

      - name: ğŸ” Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FULL_IMAGE }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: ğŸ”‘ Login to Quay.io
        run: |
          docker login quay.io -u "${{ secrets.QUAY_USER }}" -p "${{ secrets.QUAY_PASSWORD }}"

      - name: ğŸš€ Push image to Quay.io
        run: |
          docker push $FULL_IMAGE
